# Generated by Django 5.2.4 on 2025-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=30)),
                ('Tipo_documento_choice', models.CharField(choices=[('C.C', 'Cedula de Ciudadania'), ('C.E', 'Cedula de Extranjeria'), ('T.I', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], default='C.C', max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('anios_experiencia', models.PositiveIntegerField()),
                ('ciudad', models.CharField(max_length=30)),
                ('programa', models.CharField(max_length=30)),
                ('Nivel_educativo_choice', models.CharField(choices=[('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], default='MAE', max_length=30)),
                ('ficha', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
